### PR TITLE
Add alias for `as` pattern RHS

### PR DESCRIPTION
**Pull request by dcreager**
The right-hand side of an `as` expression introduces definitions, not references.  We probably need to bite the bullet and use a completely different set of nonterminals for patterns, since (I think?) not all expressions are allowed there.  But in the meantime, this alias means that we can at least distinguish the two cases.  For instance:

    (expression/identifier) @id

should only match identifiers that appear in "proper" expressions, while

    (as_pattern_target (primary_expression/identifier) @id)

should only match identifiers that appear in the RHS of an `as` expression.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
> We probably need to bite the bullet and use a completely different set of nonterminals for patterns, since (I think?) not all expressions are allowed there.

Yeah, I'm kinda curious why we don't use the existing `pattern` rule in those two cases.

**Comment by dcreager** [comment]
> Yeah, I'm kinda curious why we don't use the existing `pattern` rule in those two cases

From my (very cursory) reading, I think that's _also_ not quite the same thing.  `pattern` in our grammar is the left-hand side of an assignment, which is called [`target`](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-python-grammar-target) in the language spec.  "Patterns" in the sense of the new pattern match statements are called [`patterns`](https://docs.python.org/3/reference/compound_stmts.html#grammar-token-python-grammar-patterns) in the language spec.  One example of something that can be a `pattern` but not a `target` is a [`class_pattern`](https://docs.python.org/3/reference/compound_stmts.html#class-patterns), which matches against the constructor invocation of a class.

**Comment by theHamsta** [comment]
The patterns in pattern matching are not the same patterns that are already in the grammar. The patterns in pattern matching allow far more but are still (almost) a subset of expression (apart from the as pattern). It would be possible to copy all rules for expressions and give them the name that they would have in pattern position but I didn't want to have that code duplication for everything that can be in a pattern on the initial draft of the pattern matching PR especially since pattern can nest.

**Comment by maxbrunsfeld** [comment]
Yeah, I see. Maybe we should rename the current `pattern` to `target`. But there really is a lot in common between "pattern" and "target". Many of the "pattern" rules are already handled by "target".

>  The patterns in pattern matching allow far more but are still (almost) a subset of expression (apart from the as pattern). It would be possible to copy all rules for expressions and give them the name that they would have in pattern position but I didn't want to have that code duplication for everything that can be in a pattern on the initial draft of the pattern matching PR especially since pattern can nest.

A fair number of these rules actually already *are* duplicated, because we previously did a lot of work to differentiate between expressions and "targets" in other name-binding positions. For example, for pattern rules such as "sequence pattern", "value pattern", and "group pattern", we already parse those correctly in our existing `pattern` rule, via `attribute`, `list_pattern`, `tuple_pattern`, `splat_pattern` etc.

I'd love to see us switch away from using `expression` inside of case clauses, and lean on our existing rules that match "pattern" versions of those constructs. We'd need to add a few more variants of patterns (like `class_pattern`, and `mapping_pattern`), but I think we could parse a high percentage of patterns with just a few additions. Also, even now, using expression, there are already some patterns that probably don't parse successfully, such as capture patterns.

**Comment by maxbrunsfeld** [comment]
I'm also ok with just landing this as-is, since nobody might have time to add those missing `pattern` rules. I think we just need to be ok with making a breaking change to this in the future though, because I don't think this is quite the right structure long-term.

**Comment by patrickt** [comment]
I think that landing this as-is is fine for now (since it’s blocking some downstream work), and a breaking change will be okay when we do a major version bump.

**Comment by dcreager** [comment]
> I think we just need to be ok with making a breaking change to this in the future though, because I don't think this is quite the right structure long-term.

I completely agree with this part.  We're pinning to specific SHAs on our side, and I'm :+1: to making the necessary changes to our queries and stack graph rules as part of bumping to a new version that includes these breaking changes.  (And :crossed_fingers: we'll be able to move the stack graph rules themselves over here in the not too distant future, so they'd be updated as _part_ of making those breaking changes.)

**Pull request merged**
