### PR TITLE
Add an action to publish the grammar automatically

### PR DESCRIPTION
**Pull request by Luni-4**
This PR allows to publish automatically `tree-sitter-python` on `crates.io` when a new tag is set.

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by Luni-4** [comment]
@tausbn 

What's the status of this PR?

**Comment by tausbn** [comment]
I have no opinion on this PR. (I mostly concern myself with fixing bugs inside the grammar itself. Decisions about the the administrative aspects of `tree-sitter-python` are somewhat outside my area of expertise.)

Maybe @maxbrunsfeld could weigh in on it?

**Comment by Luni-4** [comment]
Hello @tausbn and sorry for the late reply

@maxbrunsfeld has already given consent to this action [here](https://github.com/tree-sitter/tree-sitter-java/pull/98#issuecomment-1235934619) for `tree-sitter-java` language

**Comment by amaanq** [comment]
Will supersede with my own soon

**Pull request closed without merging**
