### PR TITLE
Avoid parsing assignment LHS as an expression list

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
This will make it easier to distinguish variable *definitions* from variable *references* when consuming this syntax tree.

### CODE REVIEW

**Comment by sencer** [comment]
This commit causes the following error for me even in empty python files

```
Error detected while processing CursorHold Autocommands for "<buffer=1>":
E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:20: query: invalid node type at position 1727
```

**Comment by stsewd** [comment]
@sencer that is a problem from nvim-treesitter, not the parser. And it was fixed in the plugin already.

**Comment by theHamsta** [comment]
> @sencer that is a problem from nvim-treesitter, not the grammar. And it was fixed in the plugin already.
fixed by pinning to an older version. Updating to a 0.17.1 runtime in Neovim should fix the issue https://github.com/neovim/neovim/pull/12931

**Comment by sencer** [comment]
Thanks!

**Pull request merged**
