### PR TITLE
Update grammar to accept `except*`

### PR DESCRIPTION
**Pull request by yoff**
The official grammar now contains a new construction, `except*`, to handle exception groups.

### CODE REVIEW

**Review by tausbn — APPROVED** [review]
Looks good to me. 👍

**Comment by tausbn** [comment]
Hmm... Before merging, I wanted to take a look at the increase in the number of states before and after your changes. 

Currently, we have

```
#define LANGUAGE_VERSION 13
#define STATE_COUNT 2130
#define LARGE_STATE_COUNT 157
#define SYMBOL_COUNT 241
#define TOKEN_COUNT 105
```
and now we have 
```
#define LANGUAGE_VERSION 14
#define STATE_COUNT 2196
#define LARGE_STATE_COUNT 175
#define SYMBOL_COUNT 244
#define TOKEN_COUNT 106
```
(ignoring the ones that were unchanged).

This is somewhat larger than what I would expect from such a simple change. I wonder if it would improve matters if we moved the use of `except_group_clause` into the existing construction for `except_clause`, so that we can share the common context between these. That is, doing the following instead:

```javascript
    try_statement: $ => seq(
      'try',
      ':',
      field('body', $._suite),
      choice(
        seq(
          choice(
            repeat1($.except_clause), 
            repeat1($.except_group_clause)
          ),
          optional($.else_clause),
          optional($.finally_clause)
        ),
        $.finally_clause
      )
    ),
```

**Comment by tausbn** [comment]
Oh well. I just tested my suggestion, and it made absolutely no difference in the number of states. 🤷

**Comment by yoff** [comment]
In that case, the current PR represents a very close alignment with the official grammar...

**Comment by tausbn** [comment]
Agreed.

**Pull request merged**
