### PR TITLE
Fixes precedence issue (issue #56)

### PR DESCRIPTION
**Pull request by drjdn**
Should fix the precedence of **.

### CODE REVIEW

**Comment by patrickt** [comment]
Awesome work; thank you so much! To ensure that this doesn’t break, would you mind adding a test for the case you outlined in #56 in `corpus/expressions.txt`?

**Comment by drjdn** [comment]
Test case added as requested.

**Comment by maxbrunsfeld** [comment]
I often just leave the expectation blank initially, and then run test, and then copy the actual S-expression out of the failure message. It's not super streamlined, but it's pretty simple and it works.

**Comment by maxbrunsfeld** [comment]
Thanks a lot for fixing this @drjdn.

**Comment by drjdn** [comment]
Great, thanks for the tip!

**Pull request merged**
