### PR TITLE
Allow string prefixes to be either case

### PR DESCRIPTION
**Pull request by p-e-w**
String prefixes in Python [can be both small and capital case](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals).

Tangentially related to https://github.com/tree-sitter/tree-sitter/issues/130, although *this* is a "Type I" bug.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks! Could you add a test for at least one of these cases in the `corpus/literals.txt` file?

**Comment by p-e-w** [comment]
Done, but there is a CI failure that looks quite legitimate. Not sure what to do here.

**Comment by maxbrunsfeld** [comment]
I think you just need to regenerate the parser by running the command ‘tree-sitter generate’. Then you should be able to recompile with ‘node-gyp build’ and run these tests with ‘tree-sitter test’.

**Comment by maxbrunsfeld** [comment]
We check the generated code into the repo so that it is easy to use from languages other than JavaScript (which therefore can’t easily get the code from npm).

**Comment by p-e-w** [comment]
Thanks for finishing this, @maxbrunsfeld, and sorry for not following up sooner.

**Comment by maxbrunsfeld** [comment]
No worries! Glad to have this fixed.

**Pull request merged**
