### PR TITLE
chore: make children of `match_statement` a `case_block`

### PR DESCRIPTION
**Pull request by theHamsta**
@dcreager the children of all other indent blocks use the `block` node. It would be more consistent when `match_statement` would use the same or should there be a new name for the alternatives?

This would be more consistent for the use in queries: https://github.com/nvim-treesitter/nvim-treesitter/pull/2389/files

### CODE REVIEW

**Comment by dcreager** [comment]
That's a great catch!  I do think it makes sense to use the same name here.  You can always use `(match_statement (block))` as your query if you only want to pull put blocks from a match statement and not from any other statement type.

**Comment by dcreager** [comment]
Hmm, actually now I think I reconsider — the arms of a match aren't a list of statements, so this would break the invariant that the contents of a `block` are the same "kind" of CST, no matter where it appears.  Am I getting that right?  If so, I think it makes sense for the child of `case` to be `block`, but to choose something else for the children of `match`.  Your resulting folding query would end up as:

```
(match_statement (case_clause) @fold)
(case_clause (block) @fold)
```

That's not "consistent" in the sense of every fold being a block — but I think it's also accurate to say that not every fold in Python is a block, right?

**Comment by maxbrunsfeld** [comment]
Maybe call the indented part something different, like a `match_block`?

**Comment by dcreager** [comment]
It's called `case_block` in the [grammar](https://docs.python.org/3/reference/compound_stmts.html#the-match-statement).

Also, it looks like it was _too_ permissive to lump the pattern nonterminals in with the expression nonterminals.  That causes the following to be accepted by the parser, even though it's invalid Python:

``` py
x as y
```

**Comment by dcreager** [comment]
> Also, it looks like it was _too_ permissive to lump the pattern nonterminals in with the expression nonterminals. That causes the following to be accepted by the parser, even though it's invalid Python:

(To clarify, this was not meant to suggest that separating expressions and patterns should be part of this PR!)

**Comment by amaanq** [comment]
Can you rebase @theHamsta

**Comment by theHamsta** [comment]
@amaanq upstream has updated to expose `$._match_block` as `$.block`. This was the original intention of this PR. In the official Python grammar, this special case of block is called a `$.case_block`. Should the alias be removed and `$._match_block` be exposed as `$.case_block` or just keep the more generic `$.block` which many queries are using.

**Comment by theHamsta** [comment]
The unnecessary conflict can still be removed.

**Pull request closed without merging**
